name: Test

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world
        run: |
          echo "${{ secrets.TEST_SECRET }}"
          echo "${{ vars.WEBSITE }}" 
      - name: list
        run: ls -all
